---
- name: Ensures {{icinga2_hosts_dir}}/hosts dir exists
  file: path={{icinga2_hosts_dir}}/hosts state=directory

- name: Copy Host Definitions
  template: src=hosts_template.j2
            dest={{ icinga2_hosts_dir }}/hosts/{{ hostvars[item]['ansible_fqdn'] }}.conf
            owner=root
            group=root
            mode=0644
  with_items: "{{ groups['all'] }}"
  notify:
   - reload icinga2
